Ui/DataProvider/RecurringPayment.php
view/adminhtml/ui_component/recurring_payments_listing.xml

Add customer email to subscriptions grid.

SQMAGOPC-390: Admin user is not able locate a subscription for a particular customer and cancel it

---

Controller/Payments/Stop.php
view/frontend/templates/order/payments.phtml

'Stop subscription' button now cancels orders with status 'pending' & 'pending_payment' only.

SQMAGOPC-389: When customer cancels a subscription from "Subscriptions" page, pending orders are not cancelled

---

Model/Subscription/OrderBiller.php

Create order confirmation email after billing an order.

SQMAGOPC-402: Send order confirmation after successful order billing

---

etc/db_schema.xml

Fix error while admin deleting a customer

SQMAGOPC-404: Customers cannot be deleted after installing recurring payment

---

Model/Subscription/OrderCloner.php

Force order totals to be recalculated when quote is opened.

SQMAGOPC-399 calculate order totals again when cloning an order

---

Model/Subscription/OrderCloner.php

- Remove non scheduled products from quote
- Little clean up in this class

SQMAGOPC-413: Non recurring payment products are not stripped from order when it is cloned

---

Model/Token/Payment.php

- Change method which adding order history comments

SQMAGOPC-421: Refactor RecurringPayment Order status and comment actions to use OrderManagementInterface

---

Model/ResourceModel/Subscription/Profile.php

SQMAGOPC-422: Change invalid Recurring Profile ResourceModel parent

---

Block/Order/Payments.php
i18n/fi_FI.csv
view/frontend/templates/order/payments.phtml

- Add column with credit card number to 'My Subscriptions' grid on My account page for customer

SQMAGOPC-426: New column to My Subscriptions page in user profile

---

view/frontend/templates/order/payments.phtml

- change action links to dropdown and add new link for changing card by customer

SQMAGOPC-427: Change action column links to dropdown in My subscriptions page

---

Controller/Receipt/Index.php
Controller/Redirect/Index.php
Model/ReceiptDataProvider.php

SQMAGOPC-423: Change OrderInterface::loadByIncrementId calls to order factory implementation

---

Api/SubscriptionManagementInterface.php
Model/SubscriptionManagement.php
etc/di.xml
etc/module.xml
etc/webapi.xml
i18n/fi_FI.csv

- Creates endpoint to cancel subscription.
PS. Please check FI translations

SQMAGOPC-434: New API: Cancel recurring order

---

etc/webapi.xml

- Changed request method from GET to PUT

SQMAGOPC-434: change API request method to PUT

---

Model/SubscriptionManagement.php
i18n/fi_FI.csv

- Added validation for already closed subscriptions

SQMAGOPC-434: Block closed subscription from being canceled again

---

Controller/Card/Change.php
Controller/Payments/Stop.php

* Change exceptions for error messages

Sqmagopc 444

---

.github/workflows/code-validation.yml
composer.json

Pull request contains a github action workflow that triggers on pull requests. When a request is made, or updated the workflow is ran. At first it'll collect the changed files from the pull request. If any changed php files are found a code-validation VM is spooled up with Php 8.1 and magento-coding-standard. Once ready those are used to run a code validation against the changed files in the pull request.
Any errors or warnings found during the runtime are automatically appended to the pull request's file tab and the creator of the PR gets an email on weather the action completed or failed.
Example of what the github action warnings look like on the pull request:

SQMAGOPC-447 create github action to validate code

---

Gateway/Command/MethodProvider.php
Gateway/Http/Client/PaymentMethodProvider.php
Gateway/Request/PaymentMethodProviderDataBuilder.php
Gateway/Response/PaymentMethodProviderHandler.php
Model/ConfigProvider.php
Model/PaymentMethod/PaymentMethodDataProvider.php
etc/di.xml

* create new command for payment_providers action

SQMAGOPC-471: payment_providers - add new command for PaymentProviders call

---

Controller/Redirect/Index.php
Gateway/Command/Payment.php
Gateway/Http/Client/TransactionPayment.php
Gateway/Http/TransferFactory.php
Gateway/Request/PaymentDataBuilder.php
Gateway/Response/PaymentHandler.php
Model/Payment/PaymentDataProvider.php
Model/UrlDataProvider.php
etc/di.xml

SQMAGOPC-468: Add new command for Payment

---

Controller/Redirect/Token.php
etc/db_schema.xml

* Fix multiple subscription request

SQMAGOPC-474: Possible to create a recurring payment multiple times for a single order, which breaks order grid

---

Model/OptionSource/SelectedToken.php

* fix undefined function array_first() call

SQMAGOPC-473: Usage of dev dependency array_first breaks viewing

---

Controller/Callback/Index.php
Controller/Receipt/Index.php
Helper/ProcessPayment.php
Model/Receipt/OrderLockService.php
Model/ReceiptDataProvider.php
etc/adminhtml/system.xml

* refactor code to PHP 8.1 standards
* comment order & payment lock system for testing purpose

SQMAGOPC-465: Split ReceiptDataProvider to smaller classes p.2

---

Api/CardManagementInterface.php
Api/CustomerTokensManagementInterface.php
Api/Data/CustomerTokensResultInterface.php
Api/Data/RecurringProfileInterface.php
Api/Data/SubscriptionInterface.php
Api/Data/SubscriptionLinkInterface.php
Api/RecurringProfileRepositoryInterface.php
Api/SubscriptionLinkRepositoryInterface.php
Api/SubscriptionManagementInterface.php
Api/SubscriptionRepositoryInterface.php
Console/Command/Bill.php
Console/Command/Notify.php
Cron/RecurringPaymentBill.php
Cron/RecurringPaymentNotify.php

SQMAGOPC-504: Refactor API, Cron and Command classes to use PHP 8

---

Observer/ScheduledCartValidation.php
Plugin/PreventDifferentScheduledCart.php
etc/events.xml

* prevent place order with different scheduled product in cart

SQMAGOPC-521: Recurring payment - adding several recurring items with different schedules

---

Observer/ScheduledCartValidation.php

* fix empty cart validation for orders made from admin panel

SQMAGOPC-554: Paytrail CC Vault - fix second Paytrail payment method pt.2
